### ISSUE TITLE
1.0.4 version is broken

### ISSUE THREAD

**Issue by essential-randomness** [therealemjy/noop-ts#3]
FYI, I've been getting a "module not found" error after 1.0.4 dropped.

If you look at what's shipped in `node_modules`, `package.json` refers to the `dist` folder, but there's only the `src` folder.

Fix on this side is to lock version to `1.0.3`, but it seems like your release process is not building as it should :)

Thanks for this small but useful library!

**Comment by therealemjy** [comment]
Hi @essential-randomness 
Sorry for the late reply, for some reason I never received a notification for your issue!

Thank for taking interest in this small library. `1.0.4` was indeed broken, due to the npm version I used locally when publishing the package.
I've now fixed the issue and pushed a new version: `1.0.6`. Please let me know if you're still experiencing any problem.
